# Generated by Django 4.2.6 on 2023-12-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_actor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
