# Generated by Django 4.2 on 2023-12-26 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_filmepisode_poster_alter_filmepisode_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratefilmepisode',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
