# Generated by Django 4.2 on 2023-12-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ratefilmepisode_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
