# Generated by Django 4.2 on 2023-12-30 03:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_country_slug_alter_playlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=api.models.user_avatar_path),
        ),
    ]
