# Generated by Django 4.2 on 2023-12-30 03:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.user_avatar_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_actor',
            field=models.ManyToManyField(null=True, to='api.actor'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_category',
            field=models.ManyToManyField(null=True, to='api.category'),
        ),
    ]
