# Generated by Django 4.2 on 2023-12-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_actor',
            field=models.ManyToManyField(blank=True, null=True, to='api.actor'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_category',
            field=models.ManyToManyField(blank=True, null=True, to='api.category'),
        ),
    ]
