from django.urls import path
from api import views
from api.apis import *

urlpatterns = [
    path('api/category/', views.category_list),
    path('api/category/<int:pk>/', views.category_detail),
    path('api/country/', views.country_list),
    path('api/country/<int:pk>', views.country_detail),
    path('api/actor/', views.actor_list),
    path('api/actor/<int:pk>', views.actor_detail),
    path('api/user/', views.user_list),
    path('api/user/<int:pk>', views.user_detail),
    path('api/user_profile/', views.user_profile_list),
    path('api/user_profile/<int:pk>', views.user_profile_detail),
    path('api/film/', views.film_list),
    path('api/film/<int:pk>', views.film_detail),
    path('api/film_episode/', views.film_episode_list),
    path('api/film_episode/<int:pk>', views.film_episode_detail),
    path('api/rate_film/', views.rate_film_list),
    path('api/rate_film/<int:pk>', views.rate_film_detail),
    path('api/rate_film_episode/', views.rate_film_episode_list),
    path('api/rate_film_episode/<int:pk>', views.rate_film_episode_detail),
    path('api/comment/', views.comment_list),
    path('api/comment/<int:pk>', views.comment_detail),
    path('api/comment_film/', views.comment_film_list),
    path('api/comment_film/<int:pk>', views.comment_film_detail),
    path('api/comment_film_episode/', views.comment_film_episode_list),
    path('api/comment_film_episode/<int:pk>', views.comment_film_episode_detail),
    path('api/history/', views.history_list),
    path('api/history/<int:pk>', views.history_detail),
    path('api/tracking/', views.tracking_list),
    path('api/tracking/<int:pk>', views.tracking_detail),
    path('api/play_list/', views.play_list_list),
    path('api/play_list/<int:pk>', views.play_list_detail),
    path('api/play_list_episode/', views.play_list_episode_list),
    path('api/play_list_episode/<int:pk>', views.play_list_episode_detail),
    path('register/', RegistrationAPI.as_view()),
    path('login/', LoginAPI.as_view()),
    path('user/', UserAPI.as_view()),
]   