# Generated by Django 4.2.6 on 2023-10-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_country_alter_actor_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistepisode',
            old_name='file_episode',
            new_name='film_episode',
        ),
    ]
